services:
  - type: web
    name: JobConnect
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn jobconnect.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false