# Generated by Django 6.0.5 on 2026-05-15 22:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='compétence')),
            ],
            options={
                'verbose_name': 'Compétences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('est_candidat', models.BooleanField(default=False, verbose_name="Chercheur d'emploi")),
                ('est_recruteur', models.BooleanField(default=False, verbose_name='Recruteur')),
                ('email_verifie', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('telephone_verifie', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('badge_verifie', models.BooleanField(default=False, verbose_name='Profil vérifié')),
                ('est_suspendu', models.BooleanField(default=False, verbose_name='Suspendu')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('objet', models.CharField(max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('envoye_le', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='ProfilProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(choices=[('informatique', 'Informatique'), ('commerce', 'Commerce'), ('sante', 'Santé'), ('ingenierie', 'Ingénierie'), ('education', 'Éducation'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('rh', 'Ressources Humaines'), ('juridique', 'Juridique'), ('artisanat', 'Artisanat'), ('autre', 'Autre')], max_length=50, verbose_name='Domaine')),
                ('niveau_etude', models.CharField(choices=[('bac', 'Baccalauréat'), ('bac+2', 'BAC +2'), ('bac+3', 'Licence / BAC +3'), ('bac+4', 'Master 1 / BAC +4'), ('bac+5', 'Master 2 / BAC +5'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=50, verbose_name="Niveau d'etude")),
                ('description', models.TextField(blank=True, help_text='Décrivez votre parcours, vos motivations, vos objectifs.', verbose_name='Description personnelle')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photode profil')),
                ('localisation', models.CharField(blank=True, max_length=150, verbose_name='Localisation')),
                ('ouvert_au_travail', models.BooleanField(default=True, verbose_name='Ouvert aux opportunités')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('competences', models.ManyToManyField(blank=True, to='candidats.competence', verbose_name='Competences')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='ExperienceProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200, verbose_name='Poste')),
                ('entreprise', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('poste_actuel', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidats.profilprofessionnel')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('faux_profil', 'Faux profil'), ('spam', 'Spam / Publicité'), ('inapproprie', 'Contenu inapproprié'), ('arnaque', "Tentative d'arnaque"), ('autre', 'Autre')], max_length=20, verbose_name='Raison')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('resolu', models.BooleanField(default=False, verbose_name='Résolu')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_faits', to=settings.AUTH_USER_MODEL)),
                ('signale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'unique_together': {('auteur', 'signale')},
            },
        ),
    ]
