# Generated by Django 6.0.5 on 2026-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='envoye_par_candidat',
            field=models.BooleanField(default=False, verbose_name='Envoyé par le candidat'),
        ),
    ]
